theme: minima
title: Mods for Minecraft
author: Guga
email: guga19053@gmail.com
description: > # this means to ignore newlines until "baseurl:"
trying to create more mods for minecraft and trying to inprove them
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
